service: test

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

  	
plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
  serverless-offline:
    httpPort: 3101

functions:
  hello:
    handler: src/server.hello
    events:
      - http:
          path: /{proxy+}
          method: any
